---


# Postgres
#- src: "geerlingguy.postgresql"


# Sonatype Nexus
#- src: "git+https://gitlab.com:brian.blain/ansible-nexus.git"
#  scm: "git"


# Jenkins
- src: "geerlingguy.jenkins"


# Sonarqube
#- src: "git+https://gitlab.com/brian.blain/ansible-sonarqube.git"
